### ISSUE TITLE
Pressure Refinery Recipe

### ISSUE THREAD

**Issue by Kikiisyourfriend** [TwilightPSN/ImmersiveRevolution#151]
I was thinking maybe possibly having the Pressure Refinery use the Ember Activator instead of a furnace for crafting. Just so the Ember Activator won't be completely useless.

**Comment by TwilightPSN** [comment]
Ember Activator is the starting ember producing source  to get a mechanical pump running for the pressure refinery if you decided to not use the sink method so you need to run both at the same time
