### ISSUE TITLE
Main Menu Image Size

### ISSUE THREAD

**Issue by JakeOTwitch** [TwilightPSN/ImmersiveRevolution#16]
I use a larger display with gui scale at Large so the Background image does not adapt to the screen size.
![Screenshot (44)](https://user-images.githubusercontent.com/30060800/55761177-720c9980-5a2c-11e9-9705-6f1b3784d8b1.png)

**Comment by TwilightPSN** [comment]
Interesting its supposed to force the main menu to a specific scale ill have to look more into this one

**Comment by TwilightPSN** [comment]
Need larger image for menu most likely
