### ISSUE TITLE
Quest: Pressure Refinery Needs More Detail

### ISSUE THREAD

**Issue by JakeOTwitch** [TwilightPSN/ImmersiveRevolution#17]
The quest does not explain that the pressure refinery requires water and embers to function and that placing a metal block under the pressure refinery with lava adjacent the metal will further increase yield.
![Screenshot (45)](https://user-images.githubusercontent.com/30060800/55761350-f8c17680-5a2c-11e9-875a-80a09632abf4.png)

**Comment by TwilightPSN** [comment]
I will add more detail to this one :) trying to eliminate the need for the embers book so this will help
