### ISSUE TITLE
Hyper Diamond Not Craftable

### ISSUE THREAD

**Issue by JakeOTwitch** [TwilightPSN/ImmersiveRevolution#93]
the hyperdiamond requires the quantum flux graphite dust to be exploded and doesn't oreDict with Extreme Reactor graphite dust.

**Comment by TwilightPSN** [comment]
Will implement the inworldcrafting CT add-on to create a recipe for the graphite dust from extreme reactors

**Comment by TwilightPSN** [comment]
Implemented in 2.6 BUT its HOP Graphite Dust cuz gating
